// Behavioral contract test: the *built* parser must accept every canonical
// Event-B spelling from `rossi gen-grammars` in its proper structural role.
//
// `tokens.json` is generated by `rossi gen-grammars` from the canonical token
// tables and byte-checked on the rossi side, so it is the source of truth for
// "which spelling exists with which role". For the structural grammar, each
// spelling is embedded in a minimal component exercising that role and the
// parse must be error-free; word spellings are re-tested in uppercase
// (case-insensitivity is part of the contract); for spellings that map to
// named nodes (constants, builtins) the node type is asserted too. Finally,
// every anonymous token the templates produce must appear in
// queries/highlights.scm — this pins the ASCII→canonical alias direction (a
// dropped alias surfaces the raw ASCII token, which is not in the query) and
// keeps the hand-maintained highlight lists from drifting behind the grammar.
//
// If rossi adds a spelling or a whole class this file does not know how to
// place, the test fails — extend the maps below.

import assert from "node:assert/strict";
import { test } from "node:test";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import Parser from "tree-sitter";
import EventB from "../bindings/node/index.js";

const manifest = JSON.parse(
  readFileSync(fileURLToPath(new URL("./tokens.json", import.meta.url)), "utf8"),
);

const highlightsSource = readFileSync(
  fileURLToPath(new URL("../queries/highlights.scm", import.meta.url)),
  "utf8",
);

/** Every double-quoted token string mentioned in the highlight queries. */
const highlightedTokens = new Set(
  [...highlightsSource.matchAll(/"((?:[^"\\]|\\.)+)"/g)].map((m) =>
    m[1].replace(/\\(.)/g, "$1"),
  ),
);

const parser = new Parser();
parser.setLanguage(EventB);

/** Anonymous token types produced by every template parse in this file. */
const seenTokens = new Set();

function collectAnonymous(node) {
  if (!node.isNamed) seenTokens.add(node.type);
  for (let i = 0; i < node.childCount; i++) collectAnonymous(node.child(i));
}

/** Parse and assert the tree is error-free; returns the root node. */
function parseOk(source, spelling) {
  const root = parser.parse(source).rootNode;
  assert.equal(
    root.hasError,
    false,
    `parsing ${JSON.stringify(spelling)} in ${JSON.stringify(source)} produced: ${root.toString()}`,
  );
  collectAnonymous(root);
  return root;
}

/** Collect all node types in the tree (named and anonymous). */
function nodeTypes(node, out = new Set()) {
  out.add(node.type);
  for (let i = 0; i < node.childCount; i++) nodeTypes(node.child(i), out);
  return out;
}

/** `source` with whole-word occurrences of `spelling` uppercased. */
function uppercased(source, spelling) {
  return source.replace(new RegExp(`\\b${spelling}\\b`, "g"), spelling.toUpperCase());
}

// ---------------------------------------------------------------------------
// Structural keywords: a minimal component per keyword, tested in the
// manifest spelling and in uppercase (keywords are case-insensitive).
// INITIALISATION intentionally parses as a plain identifier event name.
const keywordTemplates = {
  context: "context C end",
  machine: "machine M end",
  end: "context C end",
  extends: "context C extends D end",
  sets: "context C sets S end",
  constants: "context C constants k end",
  axioms: "context C axioms @a x = 1 end",
  theorems: "context C theorems @t x = 1 end",
  sees: "machine M sees C end",
  refines: "machine M refines N end",
  variables: "machine M variables v end",
  invariants: "machine M variables v invariants @i v = 1 end",
  variant: "machine M variant 1 end",
  events: "machine M events event e end end",
  event: "machine M events event e end end",
  initialisation: "machine M events event initialisation then @a v ≔ 1 end end",
  any: "machine M events event e any p where @g p = 1 end end",
  where: "machine M events event e where @g x = 1 end end",
  when: "machine M events event e when @g x = 1 end end",
  with: "machine M events event e with @w x = 1 end end",
  witness: "machine M events event e witness @w x = 1 end end",
  then: "machine M events event e then @a v ≔ 1 end end",
  begin: "machine M events event e begin @a v ≔ 1 end end",
  status: "machine M events event e status ordinary end end",
};

test("every keyword spelling is accepted structurally (any case)", () => {
  for (const spelling of manifest.keyword) {
    const template = keywordTemplates[spelling];
    assert.ok(template, `no template for keyword ${JSON.stringify(spelling)}`);
    parseOk(template, spelling);
    parseOk(uppercased(template, spelling), spelling.toUpperCase());
  }
});

// ---------------------------------------------------------------------------
// Status keywords.
const statusTemplates = {
  ordinary: "machine M events ordinary event e status ordinary end end",
  convergent: "machine M events convergent event e status convergent end end",
  anticipated: "machine M events anticipated event e status anticipated end end",
  skip: "machine M events event e then @a skip end end",
  theorem: "machine M variables v invariants theorem @i v = 1 end",
};

test("every status keyword spelling is accepted structurally (any case)", () => {
  for (const spelling of manifest.status_keyword) {
    const template = statusTemplates[spelling];
    assert.ok(template, `no template for status keyword ${JSON.stringify(spelling)}`);
    parseOk(template, spelling);
    parseOk(uppercased(template, spelling), spelling.toUpperCase());
  }
});

// ---------------------------------------------------------------------------
// Atomic constants: each spelling must parse as its named node in an
// expression position.
const constantNodes = {
  bool: "bool_set",
  true: "true",
  false: "false",
  int: "integer_set",
  nat: "natural_set",
  nat1: "natural1_set",
  "ℤ": "integer_set",
  "ℕ": "natural_set",
  "ℕ1": "natural1_set",
  "∅": "empty_set",
  "{}": "empty_set",
};

test("every constant spelling parses as its named node (any case)", () => {
  for (const spelling of [...manifest.constant_word, ...manifest.constant_sym]) {
    const node = constantNodes[spelling];
    assert.ok(node, `no node mapping for constant ${JSON.stringify(spelling)}`);
    const variants =
      spelling === spelling.toUpperCase()
        ? [spelling]
        : [spelling, spelling.toUpperCase()];
    for (const variant of variants) {
      const root = parseOk(`context C axioms @a x = ${variant} end`, variant);
      assert.ok(
        nodeTypes(root).has(node),
        `expected ${JSON.stringify(variant)} to produce a (${node}) node: ${root.toString()}`,
      );
    }
  }
});

test("every builtin spelling parses as a builtin node (any case)", () => {
  for (const spelling of manifest.builtin) {
    for (const variant of [spelling, spelling.toUpperCase()]) {
      const root = parseOk(`context C axioms @a x = ${variant} end`, variant);
      assert.ok(
        nodeTypes(root).has("builtin"),
        `expected ${JSON.stringify(variant)} to produce a (builtin) node: ${root.toString()}`,
      );
      // Builtins also apply to arguments: card(S), partition(S, A).
      parseOk(`context C axioms @a x = ${variant}(S, T) end`, variant);
    }
  }
});

// ---------------------------------------------------------------------------
// Operators: each spelling is placed in a role-appropriate formula. An
// error-free parse proves the spelling lexes as one operator token in that
// role (a mis-split or identifier reading cannot complete the parse); the
// highlight-coverage test below additionally proves it surfaced as a
// canonical token.
const ROLE = {
  binary: (op) => `context C axioms @a x = a ${op} b end`,
  relop: (op) => `context C axioms @a a ${op} b end`,
  connective: (op) => `context C axioms @a a = b ${op} c = d end`,
  negation: (op) => `context C axioms @a ${op} a = b end`,
  quantifier: (op) => `context C axioms @a ${op}x · x = 1 end`,
  dot: (op) => `context C axioms @a ∀x ${op} x = 1 end`,
  pipe: (op) => `context C axioms @a S = {x ${op} x = 1} end`,
  lambda: (op) => `context C axioms @a f = ${op}x · x = 1 | x end`,
  qunion: (op) => `context C axioms @a S = ${op} x · x = 1 | {x} end`,
  prefix: (op) => `context C axioms @a x = ${op}(S) end`,
  postfix: (op) => `context C axioms @a x = r${op} end`,
  assign: (op) => `machine M events event e then @a v ${op} 1 end end`,
  becomesIn: (op) => `machine M events event e then @a v ${op} S end end`,
  becomesSuch: (op) => `machine M events event e then @a v ${op} v = 1 end end`,
};

const operatorRoles = {
  // Logical connectives and quantification.
  "∧": ROLE.connective, "&": ROLE.connective,
  "∨": ROLE.connective, or: ROLE.connective,
  "⇒": ROLE.connective, "=>": ROLE.connective,
  "⇔": ROLE.connective, "<=>": ROLE.connective,
  "¬": ROLE.negation, not: ROLE.negation,
  "∀": ROLE.quantifier, "!": ROLE.quantifier,
  "∃": ROLE.quantifier, "#": ROLE.quantifier,
  "·": ROLE.dot, ".": ROLE.dot,
  "∣": ROLE.pipe, "|": ROLE.pipe,
  "λ": ROLE.lambda, "%": ROLE.lambda,
  "⋃": ROLE.qunion, "⋂": ROLE.qunion,
  union: ROLE.qunion, inter: ROLE.qunion,
  // Comparisons.
  "=": ROLE.relop,
  "≠": ROLE.relop, "/=": ROLE.relop,
  "<": ROLE.relop, "≤": ROLE.relop, "<=": ROLE.relop,
  ">": ROLE.relop, "≥": ROLE.relop, ">=": ROLE.relop,
  "∈": ROLE.relop, ":": ROLE.relop,
  "∉": ROLE.relop, "/:": ROLE.relop,
  "⊂": ROLE.relop, "<<:": ROLE.relop,
  "⊄": ROLE.relop, "/<<:": ROLE.relop,
  "⊆": ROLE.relop, "<:": ROLE.relop,
  "⊈": ROLE.relop, "/<:": ROLE.relop,
  // Pair, relation, and set-of-relations constructors.
  "↦": ROLE.binary, "|->": ROLE.binary,
  "↔": ROLE.binary, "<->": ROLE.binary,
  "": ROLE.binary, "<<->": ROLE.binary,
  "": ROLE.binary, "<->>": ROLE.binary,
  "": ROLE.binary, "<<->>": ROLE.binary,
  "⇸": ROLE.binary, "+->": ROLE.binary,
  "→": ROLE.binary, "-->": ROLE.binary,
  "⤔": ROLE.binary, ">+>": ROLE.binary,
  "↣": ROLE.binary, ">->": ROLE.binary,
  "⤀": ROLE.binary, "+>>": ROLE.binary,
  "↠": ROLE.binary, "->>": ROLE.binary,
  "⤖": ROLE.binary, ">->>": ROLE.binary,
  "⦂": ROLE.binary, oftype: ROLE.binary,
  // Binary set and arithmetic operators.
  "∪": ROLE.binary, "\\/": ROLE.binary,
  "∩": ROLE.binary, "/\\": ROLE.binary,
  "∖": ROLE.binary, "\\": ROLE.binary,
  "×": ROLE.binary, "**": ROLE.binary,
  ";": ROLE.binary,
  "∘": ROLE.binary, circ: ROLE.binary,
  "": ROLE.binary, "<+": ROLE.binary,
  "◁": ROLE.binary, "<|": ROLE.binary,
  "⩤": ROLE.binary, "<<|": ROLE.binary,
  "▷": ROLE.binary, "|>": ROLE.binary,
  "⩥": ROLE.binary, "|>>": ROLE.binary,
  "⊗": ROLE.binary, "><": ROLE.binary,
  "∥": ROLE.binary, "||": ROLE.binary,
  "‥": ROLE.binary, "..": ROLE.binary,
  "+": ROLE.binary,
  "−": ROLE.binary, "-": ROLE.binary,
  "∗": ROLE.binary, "*": ROLE.binary,
  "÷": ROLE.binary, "/": ROLE.binary,
  mod: ROLE.binary,
  "^": ROLE.binary,
  // Prefix and postfix unary.
  "ℙ": ROLE.prefix, pow: ROLE.prefix,
  "ℙ1": ROLE.prefix, pow1: ROLE.prefix,
  dom: ROLE.prefix, ran: ROLE.prefix,
  "∼": ROLE.postfix, "~": ROLE.postfix,
  // Assignments.
  "≔": ROLE.assign, ":=": ROLE.assign,
  ":∈": ROLE.becomesIn, "::": ROLE.becomesIn,
  ":∣": ROLE.becomesSuch, ":|": ROLE.becomesSuch,
};

test("every operator spelling is accepted in its role (any case)", () => {
  for (const spelling of [...manifest.operator_sym, ...manifest.operator_word]) {
    const role = operatorRoles[spelling];
    assert.ok(role, `no role mapping for operator ${JSON.stringify(spelling)}`);
    parseOk(role(spelling), spelling);
    if (spelling !== spelling.toUpperCase() && /^[a-z]+[0-9]?$/.test(spelling)) {
      parseOk(role(spelling.toUpperCase()), spelling.toUpperCase());
    }
  }
});

test("manifest is non-empty and covers the coloured classes", () => {
  const nodes = Object.keys(manifest);
  for (const required of [
    "keyword",
    "status_keyword",
    "constant_sym",
    "constant_word",
    "builtin",
    "operator_sym",
    "operator_word",
  ]) {
    assert.ok(nodes.includes(required), `manifest is missing node class ${required}`);
    assert.ok(manifest[required].length > 0, `manifest class ${required} is empty`);
  }
});

// The reverse of the previous test: a class added to the manifest that the
// tests above do not know is a contract violation, not a silent pass.
test("every manifest class is exercised by this file", () => {
  const handled = new Set([
    "keyword",
    "status_keyword",
    "constant_sym",
    "constant_word",
    "builtin",
    "operator_sym",
    "operator_word",
  ]);
  for (const key of Object.keys(manifest)) {
    assert.ok(
      handled.has(key),
      `manifest gained class ${JSON.stringify(key)} that this file never parses — add templates for it`,
    );
  }
});

// Every anonymous token surfaced by the templates must be highlighted. This
// fails when an ASCII spelling stops aliasing to its canonical form (the raw
// ASCII token is not in highlights.scm) and when a new keyword or operator
// is added to the grammar without a matching highlight entry.
test("every canonical token the contract produces is highlighted", () => {
  assert.ok(seenTokens.size > 0, "no tokens collected — did earlier tests run?");
  for (const tokenType of seenTokens) {
    assert.ok(
      highlightedTokens.has(tokenType),
      `token ${JSON.stringify(tokenType)} is produced by the grammar but absent from queries/highlights.scm`,
    );
  }
});
