// Behavioral contract test: the *built* parser must accept every canonical
// Event-B spelling from `cargo xtask gen-grammars` in its proper structural role.
//
// `tokens.json` is generated by `cargo xtask gen-grammars` from the canonical token
// tables and byte-checked on the rossi side, so it is the source of truth for
// "which spelling exists with which role". For the structural grammar, each
// spelling is embedded in a minimal component exercising that role and the
// parse must be error-free; structural keyword spellings are re-tested in
// uppercase (their case-insensitivity is part of the contract), while the
// math/logic tokens are exact-case and tested only in their manifest spelling;
// for spellings that map to named nodes (constants, builtins) the node type is
// asserted too. Finally,
// every anonymous token the templates produce must be captured by the
// compiled queries/highlights.scm query — this pins the ASCII→canonical
// alias direction (a dropped alias surfaces the raw ASCII token, which no
// query pattern captures) and keeps the hand-maintained highlight lists from
// drifting behind the grammar.
//
// If rossi adds a spelling or a whole class this file does not know how to
// place, the test fails — extend the maps below.

import assert from "node:assert/strict";
import { test } from "node:test";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import Parser from "tree-sitter";
import EventB from "../bindings/node/index.js";

const manifest = JSON.parse(
  readFileSync(fileURLToPath(new URL("./tokens.json", import.meta.url)), "utf8"),
);

// Compiling the highlight query against the grammar also validates it: an
// unknown node or token name fails right here, mirroring `tree-sitter test`.
const highlightQuery = new Parser.Query(
  EventB,
  readFileSync(
    fileURLToPath(new URL("../queries/highlights.scm", import.meta.url)),
    "utf8",
  ),
);

const parser = new Parser();
parser.setLanguage(EventB);

/** Anonymous token types produced by every template parse in this file. */
const seenTokens = new Set();
/** The subset of seenTokens the highlight query failed to capture. */
const uncoveredTokens = new Set();

function visit(node, fn) {
  fn(node);
  for (let i = 0; i < node.childCount; i++) visit(node.child(i), fn);
}

/** Parse and assert the tree is error-free; returns the root node. */
function parseOk(source, spelling) {
  const root = parser.parse(source).rootNode;
  assert.equal(
    root.hasError,
    false,
    `parsing ${JSON.stringify(spelling)} in ${JSON.stringify(source)} produced: ${root.toString()}`,
  );
  const captured = new Set(highlightQuery.captures(root).map((c) => c.node.id));
  visit(root, (node) => {
    if (node.isNamed) return;
    seenTokens.add(node.type);
    if (!captured.has(node.id)) uncoveredTokens.add(node.type);
  });
  return root;
}

/** Parse and assert the tree carries an error; feeds no coverage sets. */
function parseFails(source, why) {
  const root = parser.parse(source).rootNode;
  assert.equal(root.hasError, true, `${why}: ${JSON.stringify(source)} parsed as ${root.toString()}`);
}

/** Collect all node types in the tree (named and anonymous). */
function nodeTypes(root) {
  const out = new Set();
  visit(root, (node) => out.add(node.type));
  return out;
}

/** `source` with whole-word occurrences of `spelling` uppercased. */
function uppercased(source, spelling) {
  return source.replace(new RegExp(`\\b${spelling}\\b`, "g"), spelling.toUpperCase());
}

/** Every spelling has a template that parses in manifest case and uppercase. */
function templatesParse(templates, spellings, what) {
  for (const spelling of spellings) {
    const template = templates[spelling];
    assert.ok(template, `no template for ${what} ${JSON.stringify(spelling)}`);
    parseOk(template, spelling);
    parseOk(uppercased(template, spelling), spelling.toUpperCase());
  }
}

// ---------------------------------------------------------------------------
// Structural keywords: a minimal component per keyword, tested in the
// manifest spelling and in uppercase (keywords are case-insensitive).
// INITIALISATION intentionally parses as a plain identifier event name.
const keywordTemplates = {
  context: "context C end",
  machine: "machine M end",
  end: "context C end",
  extends: "context C extends D end",
  sets: "context C sets S end",
  constants: "context C constants k end",
  axioms: "context C axioms @a x = 1 end",
  theorems: "context C theorems @t x = 1 end",
  sees: "machine M sees C end",
  refines: "machine M refines N end",
  variables: "machine M variables v end",
  invariants: "machine M variables v invariants @i v = 1 end",
  variant: "machine M variant 1 end",
  events: "machine M events event e end end",
  event: "machine M events event e end end",
  initialisation: "machine M events event initialisation then @a v ≔ 1 end end",
  any: "machine M events event e any p where @g p = 1 end end",
  where: "machine M events event e where @g x = 1 end end",
  when: "machine M events event e when @g x = 1 end end",
  with: "machine M events event e with @w x = 1 end end",
  witness: "machine M events event e witness @w x = 1 end end",
  then: "machine M events event e then @a v ≔ 1 end end",
  begin: "machine M events event e begin @a v ≔ 1 end end",
  status: "machine M events event e status ordinary end end",
};

test("every keyword spelling is accepted structurally (any case)", () => {
  templatesParse(keywordTemplates, manifest.keyword, "keyword");
});

// ---------------------------------------------------------------------------
// Status keywords.
const statusTemplates = {
  ordinary: "machine M events ordinary event e status ordinary end end",
  convergent: "machine M events convergent event e status convergent end end",
  anticipated: "machine M events anticipated event e status anticipated end end",
  theorem: "machine M variables v invariants theorem @i v = 1 end",
};

test("every status keyword spelling is accepted structurally (any case)", () => {
  templatesParse(statusTemplates, manifest.status_keyword, "status keyword");
});

// ---------------------------------------------------------------------------
// Atomic constants: each spelling parses as its named node. Unlike the
// structural keywords these are exact-case (kernel-language reserved words),
// so they are not re-tested in uppercase. The boolean atoms split by role:
// the predicate literals true/false/⊤/⊥ sit in predicate position, the values
// TRUE/FALSE and the BOOL type in expression position, and lowercase `bool` is
// the bool(P) conversion operator.
const constantTemplates = {
  // Expression-position atoms.
  BOOL: { src: "context C axioms @a x = BOOL end", node: "bool_set" },
  TRUE: { src: "context C axioms @a x = TRUE end", node: "bool_true" },
  FALSE: { src: "context C axioms @a x = FALSE end", node: "bool_false" },
  INT: { src: "context C axioms @a x = INT end", node: "integer_set" },
  NAT: { src: "context C axioms @a x = NAT end", node: "natural_set" },
  NAT1: { src: "context C axioms @a x = NAT1 end", node: "natural1_set" },
  "ℤ": { src: "context C axioms @a x = ℤ end", node: "integer_set" },
  "ℕ": { src: "context C axioms @a x = ℕ end", node: "natural_set" },
  "ℕ1": { src: "context C axioms @a x = ℕ1 end", node: "natural1_set" },
  "∅": { src: "context C axioms @a x = ∅ end", node: "empty_set" },
  "{}": { src: "context C axioms @a x = {} end", node: "empty_set" },
  // Predicate-position literals.
  true: { src: "context C axioms @a true end", node: "true" },
  false: { src: "context C axioms @a false end", node: "false" },
  "⊤": { src: "context C axioms @a ⊤ end", node: "true" },
  "⊥": { src: "context C axioms @a ⊥ end", node: "false" },
  // The bool(P) conversion operator (lowercase, distinct from the BOOL type).
  bool: { src: "context C axioms @a x = bool(y = z) end", node: "bool_conversion" },
};

test("every constant spelling parses as its named node", () => {
  for (const spelling of [...manifest.constant_word, ...manifest.constant_sym]) {
    const t = constantTemplates[spelling];
    assert.ok(t, `no template for constant ${JSON.stringify(spelling)}`);
    const root = parseOk(t.src, spelling);
    assert.ok(
      nodeTypes(root).has(t.node),
      `expected ${JSON.stringify(spelling)} to produce a (${t.node}) node: ${root.toString()}`,
    );
  }
});

// The kernel_lang §2.2 words split by whether they mandate a parenthesized
// argument, which is rossi's `RESERVED_OPERATOR_WORDS` split: `card`, `max`
// and `min` are closed unary expressions, `finite` and `partition` closed
// predicates, and the rest are the generic atoms that stand bare.
const CLOSED_EXPR_BUILTINS = new Set(["card", "max", "min"]);
const CLOSED_PRED_BUILTINS = new Set(["finite", "partition"]);

/** The template that applies `spelling`, and the node it must produce. */
function builtinTemplate(spelling) {
  if (CLOSED_EXPR_BUILTINS.has(spelling)) {
    return { src: `context C axioms @a x = ${spelling}(S) end`, node: "closed_unary_expression" };
  }
  if (CLOSED_PRED_BUILTINS.has(spelling)) {
    return { src: `context C axioms @a ${spelling}(S) end`, node: "builtin" };
  }
  return { src: `context C axioms @a x = ${spelling} end`, node: "builtin" };
}

test("every builtin spelling parses as its named node", () => {
  for (const spelling of manifest.builtin) {
    // Builtins are exact-case reserved words (not re-tested in uppercase).
    const t = builtinTemplate(spelling);
    const root = parseOk(t.src, spelling);
    assert.ok(
      nodeTypes(root).has(t.node),
      `expected ${JSON.stringify(spelling)} to produce a (${t.node}) node: ${root.toString()}`,
    );
  }
});

test("a closed builtin is meaningless bare or misapplied", () => {
  for (const spelling of [...CLOSED_EXPR_BUILTINS, ...CLOSED_PRED_BUILTINS]) {
    parseFails(`context C axioms @a x = ${spelling} end`, "bare closed builtin");
    parseFails(`machine M variables ${spelling} end`, "closed builtin as a name");
  }
  // A closed unary word is not an application head, so no comma list.
  parseFails("context C axioms @a x = card(S, T) end", "closed unary takes one argument");
  parseFails("context C axioms @a x = card[S] end", "a closed word is not a relation");
});

test("a generic atom stands bare but still cannot name anything", () => {
  for (const spelling of manifest.builtin) {
    if (CLOSED_EXPR_BUILTINS.has(spelling) || CLOSED_PRED_BUILTINS.has(spelling)) continue;
    parseFails(`machine M variables ${spelling} end`, "reserved atom as a name");
  }
});

test("reserved word spellings cannot name mathematical identifiers", () => {
  for (const word of [
    "NAT", "NAT1", "INT", "UNION", "INTER", "true", "false", "circ", "not", "oftype",
    "or", "POW", "POW1", "union", "inter",
  ]) {
    parseFails(`machine M variables ${word} end`, `${word} as a variable`);
    parseFails(`machine M events event e then @a ${word} ≔ 0 end end`, `${word} as an assignment target`);
  }
  parseFails("context C sets NAT end", "NAT as a carrier set");
  parseFails("context C constants POW end", "POW as a constant");
  parseFails("machine M events event e any INT end end", "INT as a parameter");
  parseFails("context C axioms @a ∀ NAT · NAT = NAT end", "NAT as a binder");
  parseFails("machine M events event e then @a POW(x) ≔ 0 end end", "POW as a function target");
  parseFails("machine M events event e then @a not(x) ≔ 0 end end", "not as a function target");
  parseOk("machine M variables Nat pow end", "case variants as names");
  parseOk("machine NAT events event POW end end", "component and event names");
  parseOk("context C axioms @a x = union(S) ∪ inter(S) end", "generalized set operators");
});

// ---------------------------------------------------------------------------
// Operators: each spelling is placed in a role-appropriate formula. An
// error-free parse proves the spelling lexes as one operator token in that
// role (a mis-split or identifier reading cannot complete the parse); the
// highlight-coverage test below additionally proves it surfaced as a
// canonical token.
const ROLE = {
  binary: (op) => `context C axioms @a x = a ${op} b end`,
  relop: (op) => `context C axioms @a a ${op} b end`,
  connective: (op) => `context C axioms @a a = b ${op} c = d end`,
  negation: (op) => `context C axioms @a ${op} a = b end`,
  quantifier: (op) => `context C axioms @a ${op}x · x = 1 end`,
  dot: (op) => `context C axioms @a ∀x ${op} x = 1 end`,
  pipe: (op) => `context C axioms @a S = {x ${op} x = 1} end`,
  lambda: (op) => `context C axioms @a f = ${op}x · x = 1 | x end`,
  qunion: (op) => `context C axioms @a S = ${op} x · x = 1 | {x} end`,
  prefix: (op) => `context C axioms @a x = ${op}(S) end`,
  postfix: (op) => `context C axioms @a x = r${op} end`,
  assign: (op) => `machine M events event e then @a v ${op} 1 end end`,
  becomesIn: (op) => `machine M events event e then @a v ${op} S end end`,
  becomesSuch: (op) => `machine M events event e then @a v ${op} v = 1 end end`,
};

const operatorRoles = {
  // Logical connectives and quantification.
  "∧": ROLE.connective, "&": ROLE.connective,
  "∨": ROLE.connective, or: ROLE.connective,
  "⇒": ROLE.connective, "=>": ROLE.connective,
  "⇔": ROLE.connective, "<=>": ROLE.connective,
  "¬": ROLE.negation, not: ROLE.negation,
  "∀": ROLE.quantifier, "!": ROLE.quantifier,
  "∃": ROLE.quantifier, "#": ROLE.quantifier,
  "·": ROLE.dot, ".": ROLE.dot,
  "∣": ROLE.pipe, "|": ROLE.pipe,
  "λ": ROLE.lambda, "%": ROLE.lambda,
  "⋃": ROLE.qunion, "⋂": ROLE.qunion,
  UNION: ROLE.qunion, INTER: ROLE.qunion,
  // Comparisons.
  "=": ROLE.relop,
  "≠": ROLE.relop, "/=": ROLE.relop,
  "<": ROLE.relop, "≤": ROLE.relop, "<=": ROLE.relop,
  ">": ROLE.relop, "≥": ROLE.relop, ">=": ROLE.relop,
  "∈": ROLE.relop, ":": ROLE.relop,
  "∉": ROLE.relop, "/:": ROLE.relop,
  "⊂": ROLE.relop, "<<:": ROLE.relop,
  "⊄": ROLE.relop, "/<<:": ROLE.relop,
  "⊆": ROLE.relop, "<:": ROLE.relop,
  "⊈": ROLE.relop, "/<:": ROLE.relop,
  // Pair, relation, and set-of-relations constructors.
  "↦": ROLE.binary, "|->": ROLE.binary,
  "↔": ROLE.binary, "<->": ROLE.binary,
  "": ROLE.binary, "<<->": ROLE.binary,
  "": ROLE.binary, "<->>": ROLE.binary,
  "": ROLE.binary, "<<->>": ROLE.binary,
  "⇸": ROLE.binary, "+->": ROLE.binary,
  "→": ROLE.binary, "-->": ROLE.binary,
  "⤔": ROLE.binary, ">+>": ROLE.binary,
  "↣": ROLE.binary, ">->": ROLE.binary,
  "⤀": ROLE.binary, "+>>": ROLE.binary,
  "↠": ROLE.binary, "->>": ROLE.binary,
  "⤖": ROLE.binary, ">->>": ROLE.binary,
  "⦂": ROLE.binary, oftype: ROLE.binary,
  // Binary set and arithmetic operators.
  "∪": ROLE.binary, "\\/": ROLE.binary,
  "∩": ROLE.binary, "/\\": ROLE.binary,
  "∖": ROLE.binary, "\\": ROLE.binary,
  "×": ROLE.binary, "**": ROLE.binary,
  ";": ROLE.binary,
  "∘": ROLE.binary, circ: ROLE.binary,
  "": ROLE.binary, "<+": ROLE.binary,
  "◁": ROLE.binary, "<|": ROLE.binary,
  "⩤": ROLE.binary, "<<|": ROLE.binary,
  "▷": ROLE.binary, "|>": ROLE.binary,
  "⩥": ROLE.binary, "|>>": ROLE.binary,
  "⊗": ROLE.binary, "><": ROLE.binary,
  "∥": ROLE.binary, "||": ROLE.binary,
  "‥": ROLE.binary, "..": ROLE.binary,
  "+": ROLE.binary,
  "−": ROLE.binary, "-": ROLE.binary,
  "∗": ROLE.binary, "*": ROLE.binary,
  "÷": ROLE.binary, "/": ROLE.binary,
  mod: ROLE.binary,
  "^": ROLE.binary,
  // Prefix and postfix unary. POW/POW1 are prefix powersets; dom/ran are the
  // closed unary applications (mandatory parens), which ROLE.prefix supplies.
  "ℙ": ROLE.prefix, POW: ROLE.prefix,
  "ℙ1": ROLE.prefix, POW1: ROLE.prefix,
  dom: ROLE.prefix, ran: ROLE.prefix,
  "∼": ROLE.postfix, "~": ROLE.postfix,
  // Assignments.
  "≔": ROLE.assign, ":=": ROLE.assign,
  ":∈": ROLE.becomesIn, "::": ROLE.becomesIn,
  ":∣": ROLE.becomesSuch, ":|": ROLE.becomesSuch,
};

test("every operator spelling is accepted in its role", () => {
  for (const spelling of [...manifest.operator_sym, ...manifest.operator_word]) {
    const role = operatorRoles[spelling];
    assert.ok(role, `no role mapping for operator ${JSON.stringify(spelling)}`);
    // Operator words are exact-case (POW, dom, …), so each is tested only in
    // its manifest spelling — uppercasing `dom` would be an ordinary identifier.
    parseOk(role(spelling), spelling);
  }
});

// The class list is an equality, not a subset check: a class the tests above
// do not know (in either direction) is a contract violation, not a silent
// pass.
test("manifest classes match this file's templates and are non-empty", () => {
  assert.deepEqual(
    Object.keys(manifest).sort(),
    [
      "builtin",
      "constant_sym",
      "constant_word",
      "keyword",
      "operator_sym",
      "operator_word",
      "status_keyword",
    ],
    "tokens.json classes changed — extend the templates in this file",
  );
  for (const [klass, spellings] of Object.entries(manifest)) {
    assert.ok(spellings.length > 0, `manifest class ${klass} is empty`);
  }
});

// Every anonymous token surfaced by the templates must be captured by the
// compiled highlight query on the actual tree. This fails when an ASCII
// spelling stops aliasing to its canonical form (no pattern captures the raw
// ASCII token) and when a new keyword or operator is added to the grammar
// without a matching highlight entry.
test("every canonical token the contract produces is highlighted", () => {
  assert.ok(seenTokens.size > 0, "no tokens collected — did earlier tests run?");
  assert.deepEqual(
    [...uncoveredTokens].sort(),
    [],
    "tokens produced by the grammar but not captured by queries/highlights.scm",
  );
});

// The coverage test above only inspects ANONYMOUS tokens (operators, keywords
// aliased to their canonical spelling). Named-node highlights — the
// boolean/set constants, the (builtin) functions, and the
// INITIALISATION event painted as @keyword by a `#match?` rule — are invisible
// to it, so pin the load-bearing ones here: a dropped @constant.builtin entry
// or a broken INITIALISATION match would otherwise ship un-/mis-highlighted to
// editors with green CI. Each row asserts the named node is captured under the
// expected highlight name (a node may also carry the generic @variable, which
// later patterns override — so this is membership, not equality).
const namedHighlights = [
  // INITIALISATION's node is a plain (identifier); the #match? rule adds @keyword.
  ["machine M events event INITIALISATION then @a v ≔ 1 end end", "identifier", "keyword"],
  ["context C axioms @a x = TRUE end", "bool_true", "constant.builtin"],
  ["context C axioms @a x = FALSE end", "bool_false", "constant.builtin"],
  ["context C axioms @a x = BOOL end", "bool_set", "constant.builtin"],
  ["context C axioms @a ⊤ end", "true", "constant.builtin"],
  ["context C axioms @a x = ∅ end", "empty_set", "constant.builtin"],
  ["context C axioms @a finite(S) end", "builtin", "function.builtin"],
];

test("load-bearing named-node highlights are applied", () => {
  for (const [source, nodeType, expected] of namedHighlights) {
    const root = parser.parse(source).rootNode;
    assert.equal(root.hasError, false, `parse error in ${JSON.stringify(source)}`);
    const pairs = highlightQuery.captures(root).map((c) => `${c.node.type}:${c.name}`);
    assert.ok(
      pairs.includes(`${nodeType}:${expected}`),
      `expected (${nodeType}) captured as @${expected} in ${JSON.stringify(source)}; got ${pairs.join(", ")}`,
    );
  }
});
