; Event-B syntax highlighting queries (tree-sitter).
;
; The captures between the markers are GENERATED by `rossi gen-grammars` from the
; canonical token tables (crates/rossi/src/{keywords,operators,builtins}.rs); run
; `rossi gen-grammars` after changing those tables. Hand-written captures for
; structural nodes go OUTSIDE the markers in the standalone grammar's
; queries/highlights.scm (editors/tree-sitter-eventb/ in the rossi monorepo) —
; the splice preserves them there, and the same command writes the Zed
; extension's bundled copy verbatim from that file. Edit only the standalone one.

; >>> rossi gen-grammars (generated, do not edit)
(keyword) @keyword
(status_keyword) @keyword
(constant_sym) @constant.builtin
(constant_word) @constant.builtin
(builtin) @function.builtin
(operator_sym) @operator
(operator_word) @operator

(comment) @comment
(string) @string
(number) @number
(label) @label
(identifier) @variable

["(" ")" "[" "]" "{" "}"] @punctuation.bracket
"," @punctuation.delimiter
; <<< rossi gen-grammars
