/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 50
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  aux_sym_context_token1 = 2,
  aux_sym_context_token2 = 3,
  aux_sym_extends_clause_token1 = 4,
  anon_sym_COMMA = 5,
  aux_sym_sets_clause_token1 = 6,
  anon_sym_EQ = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  aux_sym_constants_clause_token1 = 10,
  aux_sym_machine_token1 = 11,
  aux_sym_refines_clause_token1 = 12,
  aux_sym_sees_clause_token1 = 13,
  aux_sym_variables_clause_token1 = 14,
  sym_comment = 15,
  sym_source_file = 16,
  sym_context = 17,
  sym__context_clause = 18,
  sym_extends_clause = 19,
  sym_sets_clause = 20,
  sym_set_declaration = 21,
  sym_constants_clause = 22,
  sym_machine = 23,
  sym__machine_clause = 24,
  sym_refines_clause = 25,
  sym_sees_clause = 26,
  sym_variables_clause = 27,
  aux_sym_source_file_repeat1 = 28,
  aux_sym_context_repeat1 = 29,
  aux_sym_extends_clause_repeat1 = 30,
  aux_sym_sets_clause_repeat1 = 31,
  aux_sym_set_declaration_repeat1 = 32,
  aux_sym_machine_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym_context_token1] = "context",
  [aux_sym_context_token2] = "end",
  [aux_sym_extends_clause_token1] = "extends",
  [anon_sym_COMMA] = ",",
  [aux_sym_sets_clause_token1] = "sets",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym_constants_clause_token1] = "constants",
  [aux_sym_machine_token1] = "machine",
  [aux_sym_refines_clause_token1] = "refines",
  [aux_sym_sees_clause_token1] = "sees",
  [aux_sym_variables_clause_token1] = "variables",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_context] = "context",
  [sym__context_clause] = "_context_clause",
  [sym_extends_clause] = "extends_clause",
  [sym_sets_clause] = "sets_clause",
  [sym_set_declaration] = "set_declaration",
  [sym_constants_clause] = "constants_clause",
  [sym_machine] = "machine",
  [sym__machine_clause] = "_machine_clause",
  [sym_refines_clause] = "refines_clause",
  [sym_sees_clause] = "sees_clause",
  [sym_variables_clause] = "variables_clause",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_context_repeat1] = "context_repeat1",
  [aux_sym_extends_clause_repeat1] = "extends_clause_repeat1",
  [aux_sym_sets_clause_repeat1] = "sets_clause_repeat1",
  [aux_sym_set_declaration_repeat1] = "set_declaration_repeat1",
  [aux_sym_machine_repeat1] = "machine_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym_context_token1] = aux_sym_context_token1,
  [aux_sym_context_token2] = aux_sym_context_token2,
  [aux_sym_extends_clause_token1] = aux_sym_extends_clause_token1,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym_sets_clause_token1] = aux_sym_sets_clause_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_constants_clause_token1] = aux_sym_constants_clause_token1,
  [aux_sym_machine_token1] = aux_sym_machine_token1,
  [aux_sym_refines_clause_token1] = aux_sym_refines_clause_token1,
  [aux_sym_sees_clause_token1] = aux_sym_sees_clause_token1,
  [aux_sym_variables_clause_token1] = aux_sym_variables_clause_token1,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_context] = sym_context,
  [sym__context_clause] = sym__context_clause,
  [sym_extends_clause] = sym_extends_clause,
  [sym_sets_clause] = sym_sets_clause,
  [sym_set_declaration] = sym_set_declaration,
  [sym_constants_clause] = sym_constants_clause,
  [sym_machine] = sym_machine,
  [sym__machine_clause] = sym__machine_clause,
  [sym_refines_clause] = sym_refines_clause,
  [sym_sees_clause] = sym_sees_clause,
  [sym_variables_clause] = sym_variables_clause,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_context_repeat1] = aux_sym_context_repeat1,
  [aux_sym_extends_clause_repeat1] = aux_sym_extends_clause_repeat1,
  [aux_sym_sets_clause_repeat1] = aux_sym_sets_clause_repeat1,
  [aux_sym_set_declaration_repeat1] = aux_sym_set_declaration_repeat1,
  [aux_sym_machine_repeat1] = aux_sym_machine_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_context_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_context_token2] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_extends_clause_token1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_sets_clause_token1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_constants_clause_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_machine_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_refines_clause_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_sees_clause_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_variables_clause_token1] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_context] = {
    .visible = true,
    .named = true,
  },
  [sym__context_clause] = {
    .visible = false,
    .named = true,
  },
  [sym_extends_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_sets_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_set_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_constants_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_machine] = {
    .visible = true,
    .named = true,
  },
  [sym__machine_clause] = {
    .visible = false,
    .named = true,
  },
  [sym_refines_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_sees_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_variables_clause] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_context_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_extends_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sets_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_set_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_machine_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_target = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_target] = "target",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 0},
  [2] =
    {field_target, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == ',') ADVANCE(5);
      if (lookahead == '/') ADVANCE(1);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '{') ADVANCE(7);
      if (lookahead == '}') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(2);
      if (lookahead == '/') ADVANCE(10);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(2);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'C', 1,
        'c', 1,
        'E', 2,
        'e', 2,
        'M', 3,
        'm', 3,
        'R', 4,
        'r', 4,
        'S', 5,
        's', 5,
        'V', 6,
        'v', 6,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(8);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(15);
      END_STATE();
    case 9:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(16);
      END_STATE();
    case 10:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(19);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 14:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(22);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(23);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_context_token2);
      END_STATE();
    case 16:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 17:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(25);
      END_STATE();
    case 18:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(27);
      END_STATE();
    case 20:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(28);
      END_STATE();
    case 21:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 22:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(30);
      END_STATE();
    case 23:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 24:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 25:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(33);
      END_STATE();
    case 26:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(34);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_sees_clause_token1);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_sets_clause_token1);
      END_STATE();
    case 29:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(35);
      END_STATE();
    case 30:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(36);
      END_STATE();
    case 31:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(37);
      END_STATE();
    case 32:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(38);
      END_STATE();
    case 33:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 34:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 35:
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(41);
      END_STATE();
    case 36:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 37:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(43);
      END_STATE();
    case 38:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(44);
      END_STATE();
    case 39:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 40:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(46);
      END_STATE();
    case 41:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 42:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(48);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_context_token1);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_extends_clause_token1);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_machine_token1);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_refines_clause_token1);
      END_STATE();
    case 47:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 48:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(50);
      END_STATE();
    case 49:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(51);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_constants_clause_token1);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_variables_clause_token1);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym_context_token1] = ACTIONS(1),
    [aux_sym_context_token2] = ACTIONS(1),
    [aux_sym_extends_clause_token1] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [aux_sym_sets_clause_token1] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [aux_sym_constants_clause_token1] = ACTIONS(1),
    [aux_sym_machine_token1] = ACTIONS(1),
    [aux_sym_refines_clause_token1] = ACTIONS(1),
    [aux_sym_sees_clause_token1] = ACTIONS(1),
    [aux_sym_variables_clause_token1] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(41),
    [sym_context] = STATE(22),
    [sym_machine] = STATE(22),
    [aux_sym_source_file_repeat1] = STATE(22),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_context_token1] = ACTIONS(7),
    [aux_sym_machine_token1] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(16), 1,
      anon_sym_COMMA,
    STATE(2), 1,
      aux_sym_extends_clause_repeat1,
    ACTIONS(14), 7,
      aux_sym_context_token2,
      aux_sym_extends_clause_token1,
      aux_sym_sets_clause_token1,
      aux_sym_constants_clause_token1,
      aux_sym_refines_clause_token1,
      aux_sym_sees_clause_token1,
      aux_sym_variables_clause_token1,
  [22] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      aux_sym_context_token2,
    ACTIONS(21), 1,
      aux_sym_extends_clause_token1,
    ACTIONS(24), 1,
      aux_sym_sets_clause_token1,
    ACTIONS(27), 1,
      aux_sym_constants_clause_token1,
    STATE(3), 5,
      sym__context_clause,
      sym_extends_clause,
      sym_sets_clause,
      sym_constants_clause,
      aux_sym_context_repeat1,
  [45] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      aux_sym_context_token2,
    ACTIONS(32), 1,
      aux_sym_extends_clause_token1,
    ACTIONS(34), 1,
      aux_sym_sets_clause_token1,
    ACTIONS(36), 1,
      aux_sym_constants_clause_token1,
    STATE(6), 5,
      sym__context_clause,
      sym_extends_clause,
      sym_sets_clause,
      sym_constants_clause,
      aux_sym_context_repeat1,
  [68] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(38), 1,
      aux_sym_context_token2,
    ACTIONS(40), 1,
      aux_sym_refines_clause_token1,
    ACTIONS(42), 1,
      aux_sym_sees_clause_token1,
    ACTIONS(44), 1,
      aux_sym_variables_clause_token1,
    STATE(7), 5,
      sym__machine_clause,
      sym_refines_clause,
      sym_sees_clause,
      sym_variables_clause,
      aux_sym_machine_repeat1,
  [91] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(32), 1,
      aux_sym_extends_clause_token1,
    ACTIONS(34), 1,
      aux_sym_sets_clause_token1,
    ACTIONS(36), 1,
      aux_sym_constants_clause_token1,
    ACTIONS(46), 1,
      aux_sym_context_token2,
    STATE(3), 5,
      sym__context_clause,
      sym_extends_clause,
      sym_sets_clause,
      sym_constants_clause,
      aux_sym_context_repeat1,
  [114] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 1,
      aux_sym_refines_clause_token1,
    ACTIONS(42), 1,
      aux_sym_sees_clause_token1,
    ACTIONS(44), 1,
      aux_sym_variables_clause_token1,
    ACTIONS(48), 1,
      aux_sym_context_token2,
    STATE(9), 5,
      sym__machine_clause,
      sym_refines_clause,
      sym_sees_clause,
      sym_variables_clause,
      aux_sym_machine_repeat1,
  [137] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      anon_sym_COMMA,
    ACTIONS(14), 8,
      aux_sym_context_token2,
      aux_sym_extends_clause_token1,
      aux_sym_sets_clause_token1,
      aux_sym_constants_clause_token1,
      aux_sym_refines_clause_token1,
      aux_sym_sees_clause_token1,
      aux_sym_variables_clause_token1,
      sym_identifier,
  [154] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      aux_sym_context_token2,
    ACTIONS(54), 1,
      aux_sym_refines_clause_token1,
    ACTIONS(57), 1,
      aux_sym_sees_clause_token1,
    ACTIONS(60), 1,
      aux_sym_variables_clause_token1,
    STATE(9), 5,
      sym__machine_clause,
      sym_refines_clause,
      sym_sees_clause,
      sym_variables_clause,
      aux_sym_machine_repeat1,
  [177] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_COMMA,
    STATE(12), 2,
      sym_set_declaration,
      aux_sym_sets_clause_repeat1,
    ACTIONS(65), 4,
      aux_sym_context_token2,
      aux_sym_extends_clause_token1,
      aux_sym_sets_clause_token1,
      aux_sym_constants_clause_token1,
  [197] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(74), 1,
      anon_sym_COMMA,
    STATE(11), 2,
      sym_set_declaration,
      aux_sym_sets_clause_repeat1,
    ACTIONS(72), 4,
      aux_sym_context_token2,
      aux_sym_extends_clause_token1,
      aux_sym_sets_clause_token1,
      aux_sym_constants_clause_token1,
  [217] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_COMMA,
    STATE(11), 2,
      sym_set_declaration,
      aux_sym_sets_clause_repeat1,
    ACTIONS(77), 4,
      aux_sym_context_token2,
      aux_sym_extends_clause_token1,
      aux_sym_sets_clause_token1,
      aux_sym_constants_clause_token1,
  [237] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      sym_identifier,
    ACTIONS(83), 1,
      anon_sym_COMMA,
    STATE(17), 1,
      aux_sym_extends_clause_repeat1,
    ACTIONS(81), 4,
      aux_sym_context_token2,
      aux_sym_extends_clause_token1,
      aux_sym_sets_clause_token1,
      aux_sym_constants_clause_token1,
  [256] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    ACTIONS(89), 1,
      anon_sym_EQ,
    ACTIONS(85), 5,
      aux_sym_context_token2,
      aux_sym_extends_clause_token1,
      aux_sym_sets_clause_token1,
      aux_sym_constants_clause_token1,
      sym_identifier,
  [273] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_COMMA,
    ACTIONS(91), 1,
      sym_identifier,
    STATE(21), 1,
      aux_sym_extends_clause_repeat1,
    ACTIONS(93), 4,
      aux_sym_context_token2,
      aux_sym_extends_clause_token1,
      aux_sym_sets_clause_token1,
      aux_sym_constants_clause_token1,
  [292] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_COMMA,
    ACTIONS(95), 1,
      sym_identifier,
    STATE(20), 1,
      aux_sym_extends_clause_repeat1,
    ACTIONS(97), 4,
      aux_sym_context_token2,
      aux_sym_refines_clause_token1,
      aux_sym_sees_clause_token1,
      aux_sym_variables_clause_token1,
  [311] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_COMMA,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(2), 1,
      aux_sym_extends_clause_repeat1,
    ACTIONS(101), 4,
      aux_sym_context_token2,
      aux_sym_extends_clause_token1,
      aux_sym_sets_clause_token1,
      aux_sym_constants_clause_token1,
  [330] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_COMMA,
    ACTIONS(103), 1,
      sym_identifier,
    STATE(19), 1,
      aux_sym_extends_clause_repeat1,
    ACTIONS(105), 4,
      aux_sym_context_token2,
      aux_sym_refines_clause_token1,
      aux_sym_sees_clause_token1,
      aux_sym_variables_clause_token1,
  [349] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_COMMA,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(2), 1,
      aux_sym_extends_clause_repeat1,
    ACTIONS(107), 4,
      aux_sym_context_token2,
      aux_sym_refines_clause_token1,
      aux_sym_sees_clause_token1,
      aux_sym_variables_clause_token1,
  [368] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_COMMA,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(2), 1,
      aux_sym_extends_clause_repeat1,
    ACTIONS(109), 4,
      aux_sym_context_token2,
      aux_sym_refines_clause_token1,
      aux_sym_sees_clause_token1,
      aux_sym_variables_clause_token1,
  [387] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_COMMA,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(2), 1,
      aux_sym_extends_clause_repeat1,
    ACTIONS(111), 4,
      aux_sym_context_token2,
      aux_sym_extends_clause_token1,
      aux_sym_sets_clause_token1,
      aux_sym_constants_clause_token1,
  [406] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      aux_sym_context_token1,
    ACTIONS(9), 1,
      aux_sym_machine_token1,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    STATE(23), 3,
      sym_context,
      sym_machine,
      aux_sym_source_file_repeat1,
  [424] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
    ACTIONS(117), 1,
      aux_sym_context_token1,
    ACTIONS(120), 1,
      aux_sym_machine_token1,
    STATE(23), 3,
      sym_context,
      sym_machine,
      aux_sym_source_file_repeat1,
  [442] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_COMMA,
    ACTIONS(123), 5,
      aux_sym_context_token2,
      aux_sym_extends_clause_token1,
      aux_sym_sets_clause_token1,
      aux_sym_constants_clause_token1,
      sym_identifier,
  [456] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_COMMA,
    ACTIONS(72), 5,
      aux_sym_context_token2,
      aux_sym_extends_clause_token1,
      aux_sym_sets_clause_token1,
      aux_sym_constants_clause_token1,
      sym_identifier,
  [470] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(129), 5,
      aux_sym_context_token2,
      aux_sym_extends_clause_token1,
      aux_sym_sets_clause_token1,
      aux_sym_constants_clause_token1,
      sym_identifier,
  [484] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 4,
      aux_sym_context_token2,
      aux_sym_refines_clause_token1,
      aux_sym_sees_clause_token1,
      aux_sym_variables_clause_token1,
  [494] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 3,
      ts_builtin_sym_end,
      aux_sym_context_token1,
      aux_sym_machine_token1,
  [503] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 3,
      ts_builtin_sym_end,
      aux_sym_context_token1,
      aux_sym_machine_token1,
  [512] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 3,
      ts_builtin_sym_end,
      aux_sym_context_token1,
      aux_sym_machine_token1,
  [521] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_COMMA,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    STATE(34), 1,
      aux_sym_set_declaration_repeat1,
  [534] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 3,
      ts_builtin_sym_end,
      aux_sym_context_token1,
      aux_sym_machine_token1,
  [543] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_COMMA,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      aux_sym_set_declaration_repeat1,
  [556] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_COMMA,
    ACTIONS(152), 1,
      anon_sym_RBRACE,
    STATE(34), 1,
      aux_sym_set_declaration_repeat1,
  [569] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      sym_identifier,
    STATE(25), 1,
      sym_set_declaration,
  [579] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      sym_identifier,
    STATE(10), 1,
      sym_set_declaration,
  [589] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [597] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      sym_identifier,
  [604] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      sym_identifier,
  [611] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      sym_identifier,
  [618] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      ts_builtin_sym_end,
  [625] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_LBRACE,
  [632] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      sym_identifier,
  [639] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      sym_identifier,
  [646] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      sym_identifier,
  [653] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      sym_identifier,
  [660] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      sym_identifier,
  [667] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      sym_identifier,
  [674] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 45,
  [SMALL_STATE(5)] = 68,
  [SMALL_STATE(6)] = 91,
  [SMALL_STATE(7)] = 114,
  [SMALL_STATE(8)] = 137,
  [SMALL_STATE(9)] = 154,
  [SMALL_STATE(10)] = 177,
  [SMALL_STATE(11)] = 197,
  [SMALL_STATE(12)] = 217,
  [SMALL_STATE(13)] = 237,
  [SMALL_STATE(14)] = 256,
  [SMALL_STATE(15)] = 273,
  [SMALL_STATE(16)] = 292,
  [SMALL_STATE(17)] = 311,
  [SMALL_STATE(18)] = 330,
  [SMALL_STATE(19)] = 349,
  [SMALL_STATE(20)] = 368,
  [SMALL_STATE(21)] = 387,
  [SMALL_STATE(22)] = 406,
  [SMALL_STATE(23)] = 424,
  [SMALL_STATE(24)] = 442,
  [SMALL_STATE(25)] = 456,
  [SMALL_STATE(26)] = 470,
  [SMALL_STATE(27)] = 484,
  [SMALL_STATE(28)] = 494,
  [SMALL_STATE(29)] = 503,
  [SMALL_STATE(30)] = 512,
  [SMALL_STATE(31)] = 521,
  [SMALL_STATE(32)] = 534,
  [SMALL_STATE(33)] = 543,
  [SMALL_STATE(34)] = 556,
  [SMALL_STATE(35)] = 569,
  [SMALL_STATE(36)] = 579,
  [SMALL_STATE(37)] = 589,
  [SMALL_STATE(38)] = 597,
  [SMALL_STATE(39)] = 604,
  [SMALL_STATE(40)] = 611,
  [SMALL_STATE(41)] = 618,
  [SMALL_STATE(42)] = 625,
  [SMALL_STATE(43)] = 632,
  [SMALL_STATE(44)] = 639,
  [SMALL_STATE(45)] = 646,
  [SMALL_STATE(46)] = 653,
  [SMALL_STATE(47)] = 660,
  [SMALL_STATE(48)] = 667,
  [SMALL_STATE(49)] = 674,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [11] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_extends_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [14] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_extends_clause_repeat1, 2, 0, 0),
  [16] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_extends_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_context_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_context_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_context_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_context_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_extends_clause_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_machine_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_machine_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_machine_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_machine_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sets_clause, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_sets_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_sets_clause_repeat1, 2, 0, 0),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sets_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sets_clause, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extends_clause, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_declaration, 1, 0, 2),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_declaration, 1, 0, 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constants_clause, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sees_clause, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extends_clause, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variables_clause, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variables_clause, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sees_clause, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constants_clause, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_declaration, 5, 0, 2),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_declaration, 5, 0, 2),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sets_clause_repeat1, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_declaration, 6, 0, 2),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_declaration, 6, 0, 2),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_refines_clause, 2, 0, 3),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context, 4, 0, 1),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context, 3, 0, 1),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_machine, 4, 0, 1),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_machine, 3, 0, 1),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_set_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_set_declaration_repeat1, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [162] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_eventb(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "eventb",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
